title: Isabella McLaughlin
description: Boeing Structural Design Engineer
theme: minima
url: "https://https://github.com/inm22/PersonalWebsite/"

header_pages:
  - index.md
  - experience.md
  - education.md
